server:
  port: 5555

spring:
  cloud:
    gateway:
      routes:
        - id: chatroute
          uri: lb://CHATSERVICE
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat(?<segment>.*), ${segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: statisticsroute
          uri: lb://STATISTICSERVICE
          predicates:
            - Path=/api/statistic/**
          filters:
            - RewritePath=/api/statistic(?<segment>.*), ${segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: frontendroute
          uri: lb://FRONTEND
          predicates:
            - Path=/
          filters:
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: frontendstatisticroute
          uri: lb://FRONTEND
          predicates:
            - Path=/statistic
          filters:
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    # fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway